Property decorator
pylint-dev/pylint pull request #10057
Opened 2024-10-30 14:53 UTC by Julfried

# Enhanced support for @property decorator in pyreverse

## Type of Changes

|     | Type                   |

| --- | ---------------------- |

| ✓   | :sparkles: New feature |

## Description

Closes #9212

Closes #7644

This PR improves pyreverse's handling of Python properties by:

1. Detecting properties decorated with `@property`
2. Inferring property types from:
   - Return type annotations
   - Special handling for Enum.name property (-> str)
   - Type inference as fallback
3. Displaying properties in UML diagrams with:
   - «property» stereotype
   - Inferred type information

### Implementation Details
- Added property detection and type inference in `inspector.py`
- Properties are stored in node's `properties` list
- Types are stored in `instance_attrs_type` dictionary
- UML diagram shows property stereotype and type

### Implementation Notes

This is a first implementation to get feedback. I welcome feedback on whether this approach aligns with pyreverse's architecture and design principles.

### Future Work

Future improvements could include:

- Refactoring property handling to align with regular attribute processing

- Adding additional type inference strategies

- Add tests for property handling

2025-03-03 21:02 UTC, Julfried commented
@Pierre-Sassoulas I cleaned up my previous solution and have it actually working, when there is a property that has a return type annotated. However if there is no return type annotated it does not work, so the current test structure in `tests/data` isn`t ideal for testing this. Changing the structure however would require updating all the resulting diagrams. Not sure if I should do that?

2025-03-03 21:02 UTC, Julfried commented on pylint/pyreverse/diagrams.py
> +                    node_name = f"{node_name} : {type_annotation}"
I am not that experienced, but do you think it is possible to infer the return type using astroid in case the property is not annotated? In essence add an else branch in here

2025-03-03 21:14 UTC, Pierre-Sassoulas commented on pylint/pyreverse/diagrams.py
> +                    node_name = f"{node_name} : {type_annotation}"
In pylint we infer only and do not trust the typing (because there was no typing when pylint was created), so yes. Not sure what the philosophy in pyreverse should be. Probably that trusting the typing first then inferring makes sense (even if changing the philosophy in pylint would be humongous work and probably make pylint inconsistent).

2025-03-05 07:50 UTC, Julfried commented on pylint/pyreverse/diagrams.py
> +                    node_name = f"{node_name} : {type_annotation}"
I think this philosophy makes sense. Also assumed that pylint works that way, this is why I tried to come up with a solution using `node.infer_call_result()` however I always got `UNINFERABLE`. Probalby it is an error on my side, because I have not that much experience with astroid :)

2025-03-05 15:18 UTC, Pierre-Sassoulas commented on pylint/pyreverse/diagrams.py
> +                    node_name = f"{node_name} : {type_annotation}"
I'm not surprised you're getting uninferable, property inferring in pylint is not very good. Making property inference in astroid better would help in both pyreverse and pylint but no one worked on it as of today.

2025-03-06 16:15 UTC, Julfried commented
I guess we could fix coverage by annotating the the properties under `tests/data/property_pattern.py`. However this would mean I need to update all the test files. Maybe updating this files should be automated somehow?

2025-03-06 17:18 UTC, DudeNr33 commented
> I guess we could fix coverage by annotating the the properties under `tests/data/property_pattern.py`. However this would mean I need to update all the test files. Maybe updating this files should be automated somehow?

You can try using the functional tests for `pyreverse`. You can add new files and expected outputs below this folder: https://github.com/pylint-dev/pylint/tree/main/tests/pyreverse/functional/class_diagrams 

They are picked up automatically, and the output generated by `pyreverse` is compared to the reference output. 
If you need special command line options, or want to control what output format to create, you can create an `.rc` file to configure `pyreverse` like this: https://github.com/pylint-dev/pylint/blob/main/tests/pyreverse/functional/class_diagrams/colorized_output/colorized.rc

2025-03-07 18:45 UTC, Julfried commented
I think the pypy error is not related to my changes

2025-03-09 09:36 UTC, DudeNr33 requested changes
I feel like putting both functional tests (annotated and not annotated) into a single file fits more with the current 'one functional test file per feature/behavior', but that is personal preference. 🙂 Otherwise looks good, thanks for the fix. Let's see if adding a newsfragment also fixes the PyPy problem, as simply re-running the job did not help.

2025-03-10 09:49 UTC, Julfried commented
Added a newsfragment and merged it into 1 file. Pypy action is still failing though

2025-03-10 10:56 UTC, Pierre-Sassoulas commented
Don't bother with pypi3.10 it's failing on main too :)

2025-03-10 18:42 UTC, DudeNr33 approved these changes
Thanks again for fixing this issue!

2025-03-10 18:42 UTC, merged