Set depth
pylint-dev/pylint pull request #10077
Opened 2024-11-11 16:11 UTC by Julfried

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|    | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description
This PR adds a new `--max-depth` option to pyreverse that allows basic controlling the visualization depth of packages and classes in the generated diagrams. The depth is simply calculated by counting dots in qualified names, where depth 0 represents top-level packages/classes. 

For packages, the full path depth is considered. For classes, the depth is calculated based on their containing module to ensure meaningful class diagrams while respecting the depth limit.

Closes #9233

2024-12-14 23:56 UTC, Julfried commented
Quick update: I've completed the implementation and added tests for the --max-depth option. I believe the feature is working as intended and is ready for review. I’m currently fighting some CI issues, but they seem unrelated to my changes. Any help or advice would be much appreciated!

2024-12-15 04:09 UTC, Pierre-Sassoulas submitted a review, later dismissed
LGTM ! Don't worry about the 3.13 CI fail, this is on main too we can rebase once it's fixed. I'll also wait for a review from Andrea before merging.

2024-12-15 09:19 UTC, Julfried commented
Thanks! Appreciate your review and the clarification about the CI issue. I`ll keep an eye on any updates and am happy to rebase if needed.

2024-12-24 17:00 UTC, Pierre-Sassoulas commented
Thank you for rebasing, the mypy error is coming from main the other errors seems genuine. (Spelling is checked only in ci not in local pre-commit)

2024-12-25 09:29 UTC, Julfried commented
Thanks for pointing out the mypy error, I`ll keep an eye on it if it gets fixed in main. How about disabling spelling check for these test cases because "-" is not allowed in Python naming anyway?

2024-12-25 19:29 UTC, Pierre-Sassoulas commented on tests/pyreverse/test_writer.py
> +    - pkg.subpkg.module.submodule -> depth 3 (3 dots)
```suggestion
    - 'pkg'                  -> depth 0 (0 dots)
    - 'pkg.subpkg'           -> depth 1 (1 dot)
    - 'pkg.subpkg.module'    -> depth 2 (2 dots)
    - 'pkg.subpkg.module.submodule' -> depth 3 (3 dots)
```
Somthings's very wrong with the way the github action display pylint message but I guess this fixes the spelling

2024-12-25 19:30 UTC, Pierre-Sassoulas commented on tests/pyreverse/test_writer.py
> +    - pkg.subpkg.mod.MyClass -> depth 2 (module has 2 dots)
```suggestion
    - 'MyClass' -> depth 0 (no module)
    - 'pkg.MyClass' -> depth 0 (module has no dots)
    - 'pkg.subpkg.MyClass' -> depth 1 (module has 1 dot)
    - 'pkg.subpkg.mod.MyClass' -> depth 2 (module has 2 dots)
```

2024-12-25 22:14 UTC, Julfried commented
It seems that the spelling checks still fail, because it checks for words and ignores the quotes. How about adding these testnames to `.pylintrc` spelling dictionary?

```diff
[SPELLING]
# List of comma separated words that should not be checked.
spelling-ignore-words=subpkg,MyClass
```

2024-12-26 11:57 UTC, Julfried commented
When working on test coverage I noticed tests/data/__init__.py is empty, which impacts pyreverse's ability to detect complete package relationships. This effects validation of the --max-depth functionality since module relationships aren't fully established and the resulting diagrams do not represent the whole structure.

@Pierre-Sassoulas do you maybe remember if this was an intentional design choice, or did this just grow over time?

Note: Addressing this would require modifying all affected test files to properly reflect package relationships. Given the scope, I think handling such changes in a separate PR would be better, if we decide to do this!

2024-12-26 12:20 UTC, Pierre-Sassoulas commented
I'm not sure. Pylint had a lot of issues with namespace package and missing `__init__.py` in the past, is it the issue ? If you meant 'empty' and not 'missing' I'm not sure that an empty init.py should influence the result ?

2024-12-26 12:38 UTC, Julfried commented
Thanks for checking! You're right that it's about an empty (not missing) __init__.py. The difference is how many relationships pyreverse detects:
- Empty __init__.py: Shows only direct module dependencies [empty init file](https://is.gd/tOkhU8)
- __init__.py with imports: Shows both module dependencies and package-level relationships [imports in init file](https://is.gd/dZ7UCH) 

I think this effects depth filtering coverage since we're not testing package-level relationship filtering. Although I want to add, that I am not a testing expert.

Here is what I added to __init__.py:
```python
from .clientmodule_test import Ancestor, Specialization
from .suppliermodule_test import Interface, DoNothing, DoNothing2
from .nullable_pattern import NullablePatterns
from .property_pattern import PropertyPatterns
```

2025-01-05 22:29 UTC, Julfried commented
Thanks for your earlier guidance, Pierre!

I now rebased to fix the mypy error. Also, I made some mistakes when setting up the tests, which resulted in pyreverse generating wrong diagrams. Now I fixed it by using a proper test setup with fixtures and I test multiple depths, which improved test coverage. The issue with pyreverse not properly detecting all relationships when __init__.py still remains. I believe this is why coverage for package-level relationships is still incomplete. 

In my understanding, an empty __init__.py file limits the ability to fully establish package-level relationships, as it doesn’t define imports or explicitly link modules in the package. This might explain why pyreverse struggles with package-level filtering in such cases. However, I’m not entirely sure if this is the root cause or if there’s another factor at play.

Let me know what you think🙂

2025-01-05 23:28 UTC, Julfried commented
Thanks for your earlier guidance, Pierre!

I now rebased to fix the mypy error and addressed the spelling issues. Also, I made some mistakes when setting up the tests, which resulted in pyreverse generating wrong diagrams. Now I fixed it by using a proper test setup with fixtures and I test multiple depths, which improved test coverage. The issue with pyreverse not properly detecting all relationships when init.py still remains. I believe this is why coverage for package-level relationships is still incomplete.

In my understanding, an empty init.py file limits the ability to fully establish package-level relationships, as it doesn’t define imports or explicitly link modules in the package. This might explain why pyreverse struggles with package-level filtering in such cases. However, I’m not entirely sure if this is the root cause or if there’s another factor at play.

I’m happy to explore this further and improve the tests in a follow-up PR if needed. Let me know what you think🙂

2025-01-11 21:37 UTC, Pierre-Sassoulas reviewed
Sorry for the delay. Changes seems sensible, I have a possible refactor to suggest. (I'd like a review from Andras if possible though, no pressure @DudeNr33 ;) )

2025-01-11 21:37 UTC, Pierre-Sassoulas commented on pylint/pyreverse/writer.py
>          for rel in diagram.get_relationships("specialization"):
```suggestion
        for rel in diagram.get_relationships("specialization", depth=self.max_depth):
```
Wonder if it's possible of filtering on depth directly in ``get_relationships`` instead. Seems like it could reduce duplication of ``.should_show_node`` checks when looping on it

2025-01-13 22:38 UTC, Julfried commented
No worries, Currently I am also very packed. Will try to take a look at it later this week :)

2025-01-16 23:58 UTC, Julfried commented on pylint/pyreverse/writer.py
>          for rel in diagram.get_relationships("specialization"):
Thanks for the suggestion! I would agree, that handling everything regarding filtering in one place would benefit maintainability. However I think we still need node filtering when emitting nodes, to determine which ones to show in the final diagram. Not sure about splitting this up into 2 files either. What do you think?

2025-01-17 11:07 UTC, Julfried commented on pylint/pyreverse/writer.py
>          for rel in diagram.get_relationships("specialization"):
Actually, I feel like we could simplify this, by introducing `get_nodes()` alongside `get_relationships()`. Then the writer would look something like this.
```python
def write_packages(self, diagram: PackageDiagram) -> None:
    for module in diagram.get_nodes(depth=self.max_depth):
        # Emit node logic
    for rel in diagram.get_relationships(depth=self.max_depth):
        # Emit edge logic
```
That way all the filtering logic would be handled consistently inside the diagram classes and the printer would only need to focus on rendering the final components. What do you think?

2025-01-17 11:47 UTC, Pierre-Sassoulas commented on pylint/pyreverse/writer.py
>          for rel in diagram.get_relationships("specialization"):
Looks great !

2025-01-17 12:40 UTC, Julfried commented on pylint/pyreverse/writer.py
>          for rel in diagram.get_relationships("specialization"):
Since this is a big change, I am not sure how to approach this. Are you ok with doing this in this PR?

2025-01-19 10:52 UTC, DudeNr33 requested changes
Sorry for the delay, I am not very active on GitHub at the moment. 

Thank you for the PR - this is actually a feature I saw in a similar tool and always thought "would be really helpful to have this in pyreverse"!

Regarding the changes (and following the discussion you already had with Pierre), I feel like the logic is better suited in `diadefslib.py`, and could be handled similarly to `--show_associated`. 
But like Pierre I think handling this in a follow-up PR makes sense, so that this one does not get too big.

Besides that I only have on remark regarding the option group. 👍

2025-01-19 10:52 UTC, DudeNr33 commented on pylint/pyreverse/main.py
> +            "group": OPTIONS_GROUPS["DISPLAY"],
```suggestion
            "group": OPTIONS_GROUPS["FILTERING"],
```
I think the new option fits the FILTERING group better, as it is similar to e.g. `--show-associated`. If you agree, can you move it up near the other filtering options, as the options are also ordered in the source code accordingly?

2025-01-19 14:14 UTC, Julfried commented
Thanks, appreciate your review. Both of your suggestions make sense - especially the architectural one about moving depth filtering to diadefslib.py alongside other filters like --show_associated. I've moved the --max-depth option to the Filtering and Scope group to better align with similar options.  I am happy to do a refactor in a follow up PR :)

2025-01-20 07:48 UTC, DudeNr33 approved these changes
Thanks! Now I guess only the failing codecov check in the pipeline prevents this from being merged. 
Do you need help with that?

2025-01-20 11:54 UTC, Julfried commented
Thanks for checking! As I said here:
> Thanks for your earlier guidance, Pierre! I hope this is PR is not getting to large.
> 
> I now rebased to fix the mypy error and addressed the spelling issues. Also, I made some mistakes when setting up the tests, which resulted in pyreverse generating wrong diagrams. Now I use a proper test setup with fixtures and test multiple depths, to improve test coverage. The issue with pyreverse not properly detecting all relationships when init.py is empty still remains. I believe this is why coverage for package-level relationships is still incomplete.
> 
> In my understanding, an empty init.py file limits the ability to fully establish package-level relationships, as it doesn’t define imports or explicitly link modules in the package. This might explain why pyreverse struggles with package-level filtering in such cases. However, I’m not entirely sure if this is the root cause or if there’s another factor at play.
> 
> I’m happy to explore this further and improve the tests in a follow-up PR if needed. Let me know what you think🙂

I believe this is due to empty `__init__.py` files in `tests/data/`. Appreciate your help, if you have a better understand of what is actually happening.

2025-01-24 15:12 UTC, Julfried commented
Hey @Pierre-Sassoulas , I believe I am not able to resolve codecov, without changing the structure of the testfiles. How about merging this and doing the proposed refactor in a follow-up PR?

2025-01-24 15:41 UTC, Pierre-Sassoulas approved these changes
Let's do that !

2025-01-24 20:36 UTC, merged