Bump pylint to 3.3.2, update changelog
pylint-dev/pylint pull request #10088
Opened 2024-11-20 21:00 UTC by Pierre-Sassoulas

Other Bug Fixes
---------------

- Fixes the issue with --source-root option not working when the source files are in a subdirectory of the source root (e.g. when using a /src layout).

  Closes #10026

2024-11-20 21:13 UTC, Pierre-Sassoulas commented on examples/pylintrc
> +
Very suspicious : https://github.com/pylint-dev/pylint/issues/10009

2024-11-20 21:23 UTC, jacobtylerwalls requested changes
Ah, then let's pump the brakes until we get fixme-in-docstring extracted. (Sorry if that was me!)

2024-11-20 21:36 UTC, Pierre-Sassoulas commented
I don't understand what's happening, but I start to be suspicious of the tbump script, as the code added to the misc checker clearly isn't present in the maintenance branch.

2024-11-25 21:13 UTC, jacobtylerwalls approved these changes

2024-12-01 18:26 UTC, jacobtylerwalls approved these changes

2024-12-01 18:37 UTC, merged