Respect docstring-min-length in docparams extension
pylint-dev/pylint pull request #10104
Opened 2024-12-02 14:30 UTC by berkersal

Even though visit_functiondef is checking for docstring-min-length, it is not enough. This commit fixes the issue by adding the same check to visit_raise and visit_yield

If there is a better way of implementing this, please go forward. I am just providing a working fix to this problem.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Refs #XXXX

Closes #XXXX

2024-12-02 19:35 UTC, Pierre-Sassoulas requested changes
Thank you for opening a PR ! Would you mind adding functional tests (https://github.com/pylint-dev/pylint/tree/main/tests/functional/ext/docparams) and a changelog (https://github.com/pylint-dev/pylint/tree/main/doc/whatsnew/fragments) for this please ?

2024-12-07 14:33 UTC, Pierre-Sassoulas reviewed
Looks good thank you ! Any reasons not to create a reusable function for the new code in the doc param class (copy pasted thrice as far as I understand) ?

2024-12-07 14:35 UTC, Pierre-Sassoulas commented
Don't mind the fail of the CI this is due to https://github.com/python/cpython/pull/125415 in 3.13.1 we're going to be able to rebase on main once it's fixed.

2024-12-07 16:15 UTC, berkersal commented
Sorry for a lot of pushes 😅

2025-01-03 12:03 UTC, berkersal commented
Something not related to my changes is giving an error on pre-commit checks

2025-01-03 15:41 UTC, Pierre-Sassoulas commented
Sorry about that it's going to be fixed in #10165

2025-01-04 22:17 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +            return
Not sure it's possible to cover this, do return nodes ever have a docstring attached ?

2025-01-07 07:37 UTC, berkersal commented on pylint/extensions/docparams.py
> +            return
I'm not sure if I understand the problem 😅

2025-01-07 08:30 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +            return
Those two lines are not covered by tests, and it's in a ``visit_return`` function, so I suppose it's not covered because it's impossible to ever reach this code (return node don't have docstrings, right ?)

2025-01-07 08:33 UTC, berkersal commented on pylint/extensions/docparams.py
> +            return
I'm not sure what `return node` is but there is a part in docstrings that documents what the function is returning

2025-01-07 08:48 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +            return
Return node would be obtained from something like ``return 4``, once parsed you'll get an ast's Return node:

Parsing:
```python
print(ast.dump(ast.parse('return 4')))
```
Resut:
```
Module(body=[Return(value=Constant(value=4))])
```
(Which then become an astroid return node in pylint, before we use the visitor pattern to do something with it)

2025-01-07 08:57 UTC, berkersal commented on pylint/extensions/docparams.py
> +            return
I assume the extension is deciding the return part of the docstring from `-> int` part of the function definition. Then it wouldn't care about the return node

2025-01-07 10:08 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +            return
Hmm, would it be possible to create a functional test for it then ? (I.e. with a docstring too small and return type information that we don't need to analyse because the docstring is too small if I understood correctly)

2025-01-07 10:10 UTC, berkersal commented on pylint/extensions/docparams.py
> +            return
https://github.com/pylint-dev/pylint/pull/10104/files#diff-17555d6bcffd175b317d7430b5882ea83313a5f1a786d378b916fdb56211c147

2025-01-07 12:55 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +            return
It seems it's not covering line 345 according to codecov ? (https://app.codecov.io/gh/pylint-dev/pylint/pull/10104?src=pr&el=tree&filepath=pylint%2Fextensions%2Fdocparams.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pylint-dev#61228d78a7c97a0961324b4e7e6eb65e-R345)

2025-05-25 08:36 UTC, Pierre-Sassoulas reviewed
The added functional tests look amazing ! I authorized the workflow, let's see how it goes.

2025-05-25 17:01 UTC, berkersal commented on pylint/extensions/docparams.py
> +        return bool(min_lines > -1) and bool(lines < min_lines)
Yeah 😅. I will implement your suggestion as it is way leaner but I think the warning I was avoiding will comeback as it was about a comparison not always returning a boolean. Let's check, I forgot after 6 months 😅

2025-05-25 17:03 UTC, berkersal commented on tests/functional/ext/docparams/raise/missing_raises_doc_required_min_length.py
> +    """function is too short and is missing raise documentation"""
No we don't. This MR is about not requiring a docstring if a function has less lines than `docstring-min-length`. This is a false positive I think 🤔

2025-05-25 17:20 UTC, berkersal commented on pylint/extensions/docparams.py
> +        return bool(min_lines > -1) and bool(lines < min_lines)
It happened but it was mypy
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

pylint/extensions/docparams.py:690: error: Returning Any from function declared to return "bool"  [no-any-return]
Found 1 error in 1 file (checked 281 source files)
``` 
And the reason is basically this https://github.com/python/mypy/issues/5697#issuecomment-425738430
Not sure what is the best way to handle this case. It is also possible to assign the output of that comparison to a variable and assert the type

2025-05-25 19:09 UTC, Pierre-Sassoulas commented on pylint/extensions/docparams.py
> +        return bool(min_lines > -1) and bool(lines < min_lines)
Got it ! (I already upvoted the mypy comment you linked in the past 😄 ) Might want to use a type ignore here, when astroid is properly typed we'll remove it.

2025-06-16 10:14 UTC, berkersal commented
Sorry that I've reverted some changes accidentally last week, now it should be the correct code

2025-06-17 18:13 UTC, merged