Change _iterate_file_descrs to _get_file_items
pylint-dev/pylint pull request #10142
Opened 2024-12-18 22:10 UTC by jzohrab

Returning a materialized list instead of an iterator lets us do simple progress reporting in the future.  As the list of FileItems is very lightweight, there shouldn't be a performance hit.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Refs

This work was initially done as part of draft PR #10134 , and it makes sense as a small refactor of the internal method.

2024-12-18 22:23 UTC, Pierre-Sassoulas commented
Why not just call ``list`` on the iterator instead of refactoring everything ?

2024-12-18 22:37 UTC, jzohrab commented
> Why not just call `list` on the iterator instead of refactoring everything ?

Good question.  Either way, it kind of ends up being the same thing: we either edit code so that we do `list(iterator)` everywhere, or we return a list and change code that uses it.  Since this is an internal method, and the content is always only used as a list (to facilitate progress logging), it made sense for the code to reflect that intent.

2024-12-18 23:47 UTC, DanielNoord approved these changes
Awesome!

If Pierre agrees let's merge this!

2024-12-18 23:52 UTC, DanielNoord requested changes
Uhhh, this seems to fail CI? 😅 

Is that an actual failure? And if so, do you understand why?

2024-12-19 00:26 UTC, jzohrab commented
Will check it out, thank you @DanielNoord.

2024-12-19 00:44 UTC, jzohrab commented
@DanielNoord - this failure actually exists in commit cb125773cf, immediately prior to my two new commits.

I went back a bit just using git reset, and unless there are steps that I'm missing, at appears that this error has been present since at least 713e563edf (Thu Oct 5 22:12:56 2023 +0200, Merge branch 'maintenance/3.0.x' into merge-maintenance-into-main):

```
$ pytest -k test_one_module_fatal_error

...
>       assert pylint_code == code, msg
E       AssertionError: expected output status 1, got 3. Below pylint output: 
E         ************* Module /Users/jeff/Documents/Projects/pylint/tests/garbagePath.py
E         tests/garbagePath.py:1:0: F0001: No module named tests/garbagePath.py (fatal)
E         ************* Module conftest
E         tests/conftest.py:10:0: E0401: Unable to import 'collections.abc' (import-error)
E         
E         -----------------------------------
E         Your code has been rated at 0.00/10
E         
E         
E       assert 3 == 1
```

I haven't read the tests, but I'm assuming that each test can be run independently (no global state trash etc).  When I run all of the tests as at that commit 713e563edf, I get a bunch of failures, including that bad test `FAILED tests/test_self.py::TestRunTC::test_one_module_fatal_error - AssertionError: expected output status 1, got 3. Below pylint output: `

Just for fun, rechecking cb125773cf which was the base of my branch:

```  ... checkout
HEAD is now at cb125773c [skip ci] Add python 3.13 to tox configuration
(venv) MacBook-Pro:pylint jeff$ pytest
...
FAILED tests/test_self.py::TestRunTC::test_one_module_fatal_error - AssertionError: expected output status 1, got 3. Below pylint output: 
================================= 24 failed, ... etc
```

I got few failures than the older commit, but that same test failed (on my machine).

2024-12-19 01:04 UTC, jzohrab commented
If we change the `code=1` arg to 3, that test now passes (locally), though I have no idea why.

```
    def test_one_module_fatal_error(self) -> None:
        """Fatal errors in one of several modules linted still exits non-zero."""
        valid_path = join(HERE, "conftest.py")
        invalid_path = join(HERE, "garbagePath.py")
        self._runtest([valid_path, invalid_path, "--disable=C"], code=3)
```

Here's git blame for that function, it's been around a while:

```
6417e8cdee (Pierre Sassoulas      2022-07-14     def test_one_module_fatal_error(self) -> None:
fffde57ac0 (Daniël van Noord      2022-01-02         """Fatal errors in one of several modules linted still exits non-zero."""
af8cc2e750 (Jacob Walls           2021-12-14         valid_path = join(HERE, "conftest.py")
af8cc2e750 (Jacob Walls           2021-12-14         invalid_path = join(HERE, "garbagePath.py")
8482d2ee74 (Pierre Sassoulas      2022-04-22         self._runtest([valid_path, invalid_path, "--disable=C"], code=1)
```

Cheers!

2024-12-19 08:31 UTC, Pierre-Sassoulas requested changes
>  As the list of FileItems is very lightweight

I'm not sure this is always true, and I'm not sure it's the main consideration. We need to understand why it was done this way before changing it (the first implementation is not often an iterator for no good reasons). 

I don't have the time to read everything right now but I dug into the git history and here's the MR that introduced this:

https://github.com/pylint-dev/pylint/pull/3016

Last comment might be interesting: https://github.com/pylint-dev/pylint/pull/3016#issuecomment-987725203

2025-01-11 22:15 UTC, Pierre-Sassoulas commented
Sorry for not answering very fast, life got in the way. Do you mean something like a file counter inside the iterator loop to be able to know how many file were processed ? Sounds good to me because I think keeping the iterator is better. Multiprocessing didn't get much love yet, so I'm not definitely certain an iterator is required for multiprocessing, and it's just me being cautious and assuming the author and reviewers of #3016 knew what they were doing.

2025-01-11 22:32 UTC, jzohrab commented
Not a problem @Pierre-Sassoulas , I appreciate that this is open source so we all do what we can.

I’ll try to submit a smaller PR soon, let’s keep this open until that one is submitted just so people know it’s in progress. Cheers, jz

2025-01-12 02:59 UTC, jzohrab commented
Closing this per @Pierre-Sassoulas 's feedback.  I've opened a simpler PR for progress reporting, #10178 , which doesn't require any iterator changes.  Thanks :wave:

2025-01-12 02:59 UTC, closed without merging