Cython pure python declare
pylint-dev/pylint pull request #8025
Opened 2023-01-05 12:50 UTC by jtoledo1974

## Type of Changes

|     | Type                   |
| --- | ---------------------- |

## Description

This Pull Requests provides a test case for #8024.
A pure python cython.declare(cython.int... is reported as no-member. These should be ignored.

Refs #8024

Closes #XXXX

2023-01-05 16:11 UTC, jtoledo1974 commented
@Pierre-Sassoulas , I took a look at it. Both pure python cython problems get resolved by ignoring the cython module. I took a look to see whether this would be a problem for the cython developers, but they themselves don't seem to do cimports.

Problem is that just setting a default for ignored-imports doesn't cut it because it would be overridden by any user configuration.

The option reading code is complex and I don't know where in the codebase it is that you would like to have the forced ignored-import added. I'll do it if you give me a hint.

2023-01-06 11:45 UTC, mbyrnepr2 commented on doc/whatsnew/fragments/8024.false_positive
> +Added test for pure python cython.declare usage, which should be valid no matter what is imported from the cython module.
```suggestion
Added test for pure Python ``cython.declare`` usage, which should be valid no matter what is imported from the cython module.
```

2023-01-06 11:46 UTC, mbyrnepr2 commented on tests/functional/r/regression_02/regression_cython_declare_8024.py
> +"""Test for cython pure python false positives"""
```suggestion
"""Test for cython pure Python false positives"""
```

2023-01-06 11:47 UTC, mbyrnepr2 commented on tests/functional/r/regression_02/regression_cython_declare_8024.py
> +# Check that it doesn't raise neither an import-error nor a
```suggestion
# Check that it raises neither an import-error nor a
```

2023-01-06 11:47 UTC, mbyrnepr2 commented on tests/functional/r/regression_02/regression_cython_declare_8024.py
> +# cython allows any import in pure python mode. It can only
```suggestion
# cython allows any import in pure Python mode. It can only
```

2023-01-10 13:11 UTC, DanielNoord requested changes
We don't test with `cython` right? So this PR doesn't make a lot of sense in its current state imo.

2023-01-11 09:07 UTC, jtoledo1974 commented
> We don't test with `cython` right? So this PR doesn't make a lot of sense in its current state imo.

The point of the matter is that this is not just cython code. It is valid python interpreted code. Cython allows to compile it as well, but it shouldn't be flagged as invalid.

2023-01-11 20:09 UTC, DanielNoord commented
> > We don't test with `cython` right? So this PR doesn't make a lot of sense in its current state imo.
> 
> The point of the matter is that this is not just cython code. It is valid python interpreted code. Cython allows to compile it as well, but it shouldn't be flagged as invalid.

I don't really understand your point. I was just saying that this test will never run in CI which is why this PR has a successful CI even though there is no fix for the added test.

2023-01-11 23:08 UTC, jtoledo1974 commented
> > > We don't test with `cython` right? So this PR doesn't make a lot of sense in its current state imo.
> > 
> > 
> > The point of the matter is that this is not just cython code. It is valid python interpreted code. Cython allows to compile it as well, but it shouldn't be flagged as invalid.
> 
> I don't really understand your point. I was just saying that this test will never run in CI which is why this PR has a successful CI even though there is no fix for the added test.

I apologize. I misunderstood and my choice of words was poor.

I was forcing the test to run to make sure that it failed first and then it passed. I would say it was run together with the other tests after a full run, but I can't say for sure. But if CI passes I guess it didn't.

2024-06-03 20:18 UTC, closed without merging