Add CITATION.cff
pylint-dev/pylint pull request #8765
Opened 2023-06-12 16:13 UTC by schackartk

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

This pull request adds a CITATION.cff file to the root of the repository which contains all the necessary metadata to properly cite Pylint.

Closes #8760

## Further Considerations

I have drafted an initial version of this file, but it is up to the maintainers what information to include. Some items for further consideration:

- Any preference on the author field? Some projects do not include any individuals, but I opted to include @Pierre-Sassoulas then wrap everyone else in "Pylint contributors". How this is worded is entirely optional.
- If including @Pierre-Sassoulas explicitly, do you have an ORCiD you would like to include?
- Any revisions of the abstract?
- CFF has a `release-date` field. Some projects put the year of first release there.
- CFF also has a `version` field, but it is generally not included. It must be kept up to date which adds friction, and most citation formats will not use the information anyway.

Also, I ran `tox -e docs`, but I am not sure if it ran succesfully. Certain files were changed in ways that I didn't think needed to be commited (`docs/user_guide/checkers/features.rst`, `docs/user_guide/configuration/all-options.rst`, and `doc/user_guide/messages/message_overview.rst`).

2023-06-12 16:21 UTC, Pierre-Sassoulas reviewed
Thank you for opening the merge request !

2023-06-12 16:23 UTC, schackartk commented on CITATION.cff
> +  - name: "Pylint contributors"
I will go with your second option. Should it be "Pylint" or "pylint" though?

2023-06-12 16:28 UTC, Pierre-Sassoulas commented
> CFF has a release-date field. Some projects put the year of first release there.

That would be 2003

> CFF also has a version field, but it is generally not included. It must be kept up to date which adds friction, and most citation formats will not use the information anyway.

This can be updated automatically with tbump see https://github.com/pylint-dev/pylint/blob/main/tbump.toml#L22

> Also, I ran tox -e docs, but I am not sure if it ran succesfully. Certain files were changed in ways that I didn't think needed to be commited (docs/user_guide/checkers/features.rst, docs/user_guide/configuration/all-options.rst, and doc/user_guide/messages/message_overview.rst).

Yeah don't worry, this is not always up-to-date. Also there's a problem with the documentation check in the CI right now see #8762, so we're definitely going to update the doc in this one.

2023-06-12 16:29 UTC, Pierre-Sassoulas commented on CITATION.cff
> +  - name: "Pylint contributors"
Not sure, ``pylint`` is used in package manager and the like so pylint without capitalization also make sense but I remember we talked about it at some point when working on the doc. Maybe another maintainer will remember what was decided.

2023-06-12 18:41 UTC, Pierre-Sassoulas commented
Didn't think of the date that should change too, what about ``current`` ?

2023-06-13 15:58 UTC, Pierre-Sassoulas requested changes
Could you rebase on the upstream main branch please, @jacobtylerwalls fixed the issue with the doc check :)

2023-06-13 15:58 UTC, Pierre-Sassoulas commented on CITATION.cff
> +    given-names: Pierre
```suggestion
```

2023-06-13 16:41 UTC, DanielNoord commented on CITATION.cff
> +  - name: "Pylint contributors"
We decided to leave it undecided I think haha
I think it makes sense to capitalise at the beginning of a sentence but keep it lower case anywhere else

2023-06-13 17:31 UTC, closed without merging

2023-06-13 17:46 UTC, schackartk commented
Yes, so sorry! I just wrapped up a different pull request and deleted the wrong repository >.< . I re-forked it and restored the branch, but I am unsure how to reopen the PR.

(Thanks for bearing with me, still a bit new to all this!)

2023-06-13 17:47 UTC, schackartk commented
Reopen PR

2023-06-13 17:55 UTC, Pierre-Sassoulas commented
I think you need to refork pylint ? 

![repodeleted](https://github.com/pylint-dev/pylint/assets/5493666/0cc0abf9-60a5-4a04-b3f4-957c28f7015c)

2023-06-14 07:37 UTC, Pierre-Sassoulas commented
Don't worry I re-created it in https://github.com/pylint-dev/pylint/pull/8777 and credited you by signing the commit with your email.