Fix a false positive for ``no-member``.
pylint-dev/pylint pull request #8778
Opened 2023-06-14 14:50 UTC by mbyrnepr2

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

Fix a false positive for ``no-member`` when accessing a no-value attribute that is annotated in a class body.

Closes 8759

2023-08-16 05:44 UTC, Pierre-Sassoulas commented
Is it still a draft @mbyrnepr2 ?

2023-08-16 07:12 UTC, mbyrnepr2 commented
Thanks for the reminder @Pierre-Sassoulas. It’s been a while since I thought about it and I think I must have had a doubt about it to leave it as a draft. 
A review/feedback would be helpful to see if this change makes sense.

2023-08-17 20:39 UTC, Pierre-Sassoulas requested changes
I think we need to do something specific to pydantic(s Base Model to treat it correctly erven if it's dynamic (maybe a brain in astroid, maybe an external plugin) but I'm not a pydantic user so I don't know exactly how BaseModel is supposed to behave.

2023-08-17 20:41 UTC, Pierre-Sassoulas commented on tests/functional/n/no/no_member_augassign.py
> +obj_a.value += 1
A review comment got lost: Here we'd introduce a false negative, running the code raise an error:
```
Traceback (most recent call last):
  File "/home/pierre/pylint/doc/a.py", line 12, in <module>
    obj_a = A(1)
TypeError: A() takes no arguments
```

2024-04-05 12:00 UTC, closed without merging