renamed unneeded-not
pylint-dev/pylint pull request #8846
Opened 2023-07-12 18:49 UTC by gracejiang16

Not functional yet; trying to work on deprecated name

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Refs #XXXX

Closes #XXXX

2023-07-13 19:05 UTC, Pierre-Sassoulas commented on .gitignore
> +/venv
You can use a global gitignore for that :)

2023-07-13 19:05 UTC, Pierre-Sassoulas commented on tests/functional/u/unnecessary/unnecessary_negation.py
> +"""Check exceeding negations in boolean expressions trigger warnings"""
It's strange that everything changed here, probably due to modified end of line (``\r\n`` vs ``\n```). Could you revert to the original line ending ? It preservs the git blame and we need some diversity in line ending in some of the tests which is why it's not uniformized with a ``.gitattributes`` :)

2023-08-06 02:52 UTC, jacobtylerwalls commented
Thanks for the contribution @gracejiang16!

2023-08-06 02:52 UTC, jacobtylerwalls approved these changes

2023-08-06 03:05 UTC, merged

2023-08-06 18:01 UTC, Pierre-Sassoulas requested changes
Great work, thank you !

2023-08-06 18:01 UTC, Pierre-Sassoulas commented on doc/whatsnew/fragments/8789.other
> +Renamed the "unneeded-not" error into "unnecessary_negation" to be clearer.
```suggestion
Renamed the "unneeded-not" error into "unnecessary-negation" because it can be raised on comparator not using the `not` keyword.
```