Check that a name exists inside `enum.Enum` class' `__members__`.
pylint-dev/pylint pull request #8905
Opened 2023-07-31 12:42 UTC by mbyrnepr2

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

Check that a name exists inside an `enum.Enum` class' `__members__` container before doing the ``invalid-name`` check.

Refs #7402

2023-07-31 12:42 UTC, mbyrnepr2 commented on pylint/checkers/base/name_checker/checker.py
> +                    if (is_enum_member) or utils.is_assign_name_annotated_with(
Any shouts for a re-usable function "enum member" function here instead?

2023-08-03 12:11 UTC, mbyrnepr2 commented
There’s 2 warnings in the readthedocs output that are failing the ci but unsure which file it’s coming from exactly. Seems to be 3.0/index

2023-08-04 06:56 UTC, Pierre-Sassoulas commented
I'm going to try to fix the readthedoc pipeline on main.

2023-08-04 11:19 UTC, mbyrnepr2 commented
> 🤖 **Effect of this PR on checked open source code:** 🤖
> 
> **Effect on [music21](https://github.com/cuthbertLab/music21):** The following messages are now emitted:
> 
> 1. invalid-name:
>    _Class attribute name "registerOutputSubformatExtensions" doesn't conform to '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.___))$' pattern*
>    https://github.com/cuthbertLab/music21/blob/8baa27339109895cc4c55dd99cb0290e111fb02a/music21/converter/subConverters.py#L355
> 2. invalid-name:
>    _Class attribute name "registerOutputSubformatExtensions" doesn't conform to '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.___))$' pattern*
>    https://github.com/cuthbertLab/music21/blob/8baa27339109895cc4c55dd99cb0290e111fb02a/music21/converter/subConverters.py#L411
> 3. invalid-name:
>    _Class attribute name "registerOutputSubformatExtensions" doesn't conform to '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.___))$' pattern*
>    https://github.com/cuthbertLab/music21/blob/8baa27339109895cc4c55dd99cb0290e111fb02a/music21/converter/subConverters.py#L834
> 
> _This comment was generated for commit [83a3503](https://github.com/pylint-dev/pylint/commit/83a35034757f2d77cb7a5fa822bec8e4543c1e12)_

These seem valid because the names are too long for the regex defined in that project's pylintrc:
```python
import re
>>> re.match("([A-Za-z_][A-Za-z0-9_]{2,30}|(__.__))$", "registerOutputSubformatExtensions")
>>> 
```

2023-08-04 20:22 UTC, Pierre-Sassoulas reviewed
It would mean we never raise on an enum ? In the example with color and rgb the color is a three ints tuple and red/green/blue is simply an int maybe it's something to explore ?

2023-08-04 20:59 UTC, mbyrnepr2 commented
@Pierre-Sassoulas in the context of the example you refer to, the message doesn't raise and that is the expected outcome since the members satisfy the checker and the attributes are not assigned values (hence they don't appear in the `__members__` container). However, you need to also checkout the astroid branch https://github.com/pylint-dev/astroid/pull/2263 to see it working correctly.

2023-08-05 04:57 UTC, Pierre-Sassoulas requested changes
Right my bad didn't see that the functional test was actually raising here. Could you add the rgb example as a functional test ? LGTM otherwise.

2023-08-05 07:39 UTC, mbyrnepr2 commented
Unittests will fail now until https://github.com/pylint-dev/astroid/pull/2263 is released.
About that - I currently have the astroid change set for 3.0 release but would you prefer that to be changed to 2.15.7 instead?

2023-08-05 15:13 UTC, Pierre-Sassoulas reviewed
I liked your own functional test too, we can have both :) otherwise LGTM

2023-08-05 15:14 UTC, Pierre-Sassoulas commented
Is it a bug fix il astroid ? If so we can backport it. If  not let's release this in 3.0

2023-08-07 11:16 UTC, mbyrnepr2 commented
> Is it a bug fix il astroid ? If so we can backport it. If not let's release this in 3.0

It's a bug-fix in both astroid and Pylint (if I've understood you correctly :))
astroid fix: exclude non-members from  `__members__` (i.e: `tomato: int`)
pylint fix: check that the `AssignName` belongs to the `__members__` of it's class (and not only check that the class is a subtype of `enum.Enum`.)

2023-08-07 11:17 UTC, mbyrnepr2 commented
> I liked your own functional test too, we can have both :) otherwise LGTM

No worries - less is more :)

2023-08-07 12:20 UTC, Pierre-Sassoulas commented
Blocked by the releease of astroid 2.15.7 then ?

2023-08-07 12:26 UTC, mbyrnepr2 commented
It's also blocked by https://github.com/pylint-dev/pylint/issues/8897 run with the code in the current MR crashes 😢

2023-08-07 12:44 UTC, mbyrnepr2 commented
> It's also blocked by #8897 since the code in that example when run with the Pylint code of the current MR crashes 😢

But I may have a fix for that shortly :)

2023-09-23 21:48 UTC, jacobtylerwalls commented
@mbyrnepr2 do you know why tests are passing without your astroid changes here?

2023-09-24 05:59 UTC, mbyrnepr2 commented
I think the changes from astroid were pulled in from latest push? 2.15.7 astroid went out last month I think. There’s been a couple of different enum changes.

2023-09-24 06:03 UTC, Pierre-Sassoulas approved these changes

2023-09-24 12:47 UTC, jacobtylerwalls commented
2.15.7 went out yesterday, and we haven't updated pylint to that or to a new astroid pre-release.

2023-09-24 12:48 UTC, jacobtylerwalls commented
Ooh, Pierre is doing the pre-release right now!

2023-09-24 13:12 UTC, Pierre-Sassoulas commented
We have both 2.15.7 and 3.0.0b0 released now, so it should be possible to merge on main then backport.

2023-09-26 19:57 UTC, merged

2024-07-07 16:48 UTC, jacobtylerwalls commented on pylint/checkers/base/name_checker/checker.py
>              if not list(frame.local_attr_ancestors(node.name)):
Unfortunately, removing this line caused #9765