fix unnecessary-comprehension provides incorrect suggestion
pylint-dev/pylint pull request #9172
Opened 2023-10-21 15:45 UTC by C0DE-SLAYER

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Refs #9109

2023-10-21 16:23 UTC, jacobtylerwalls commented
Thanks for the patch!

Based on the test results, you'll notice you'll need to adjust the logic of #4500 to make it a little dumber (and therefore more like the original intent of #2999).

2023-10-22 09:29 UTC, C0DE-SLAYER commented
@jacobtylerwalls i am a beginner and having a hard time solving can you help me what i have to do to solve the issue. it would be a great help! thanks

2023-10-22 09:41 UTC, Pierre-Sassoulas commented
I'm on mobile si I can't link the specific code but  the message is raised in the add_message function, the message is dynamic and the argument given to add_message used in %s later is what need to be modified.

2023-10-27 20:45 UTC, Pierre-Sassoulas requested changes
Thank you for your contribution, it looks promising, do you mind adding the functional tests from #8577 
```python
a = [[1, 2], [3, 4]]
b = [(x, y) for x, y in a]  # flagged as unnecessary-comprehension
```
And #9109:
```python
#pylint: disable=missing-module-docstring
a = [1, 2, 3]
b = [x for x in a]
b[0] = 0
print(a) # [1, 2, 3]
```
in tests/functional/u/unnecessary/unnecessary_comprehension.py, please ?

2023-10-27 20:46 UTC, Pierre-Sassoulas commented
Also a bug / or false positive changelog fragment would be nice for this one.

2023-10-28 10:24 UTC, C0DE-SLAYER commented
> Thank you for your contribution, it looks promising, do you mind adding the functional tests from #8577
> 
> ```python
> a = [[1, 2], [3, 4]]
> b = [(x, y) for x, y in a]  # flagged as unnecessary-comprehension
> ```
> 
> And #9109:
> 
> ```python
> #pylint: disable=missing-module-docstring
> a = [1, 2, 3]
> b = [x for x in a]
> b[0] = 0
> print(a) # [1, 2, 3]
> ```
> 
> in tests/functional/u/unnecessary/unnecessary_comprehension.py, please ?

in the unnecessary_comprehension.py on line 5 it can be use for 9109 and 
for 8577  ' [(x, y) for x, y in iterable]  # [unnecessary-comprehension] ' is this good

2023-10-28 17:46 UTC, jacobtylerwalls commented
> where to do that in the doc/whatsnew/fragment or any where else and what it would be helpfull thanks!

Check out the [contributor docs](https://pylint.readthedocs.io/en/latest/development_guide/contributor_guide/contribute.html#creating-a-pull-request) for some info on documenting your pull request.

2023-11-14 17:17 UTC, jacobtylerwalls reviewed
Thanks for the news entry! Spotted one typo.

2023-11-15 08:34 UTC, C0DE-SLAYER commented on doc/whatsnew/fragments/9172.false_positive
> +Fixed `unnecessary-comprehension provides incorrect suggestion`
Fixed incorrect suggestion for shallow copy in unnecessary-comprehension
does this look good

2023-11-15 19:55 UTC, jacobtylerwalls commented
Thanks for the contribution! :gift:

2023-11-17 12:27 UTC, jacobtylerwalls approved these changes

2023-11-17 12:27 UTC, merged