Fixed false positive nested-min-max for nested lists
pylint-dev/pylint pull request #9323
Opened 2023-12-24 05:52 UTC by udifuchs

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Nesting is useful for finding the maximum in a matrix.
Therefore, pylint now allows nesting of the form:
```
max(max([[1, 2, 3], [4, 5, 6]]))
```

Closes #9307

2023-12-25 13:50 UTC, jacobtylerwalls commented on tests/functional/n/nested_min_max.py
> +# No message if extrenal call has exactly 1 argument
Hey! Hope to find time for a review soon. In the meantime, a small typo:
```suggestion
# No message if external call has exactly 1 argument
```

2023-12-26 15:10 UTC, Pierre-Sassoulas requested changes
LGTM, great fix ! I'd like to see the primer's result before merging,, I think it depends on 
#9330 being merged and then a rebase on it.

2023-12-27 11:33 UTC, Pierre-Sassoulas commented
It can be rebased now :)

2023-12-30 18:51 UTC, Pierre-Sassoulas approved these changes
Good job fixing the primers @jacobtylerwalls :)

2023-12-30 18:52 UTC, merged