Check for all set-length-modifying methods in modified-iterating-set
pylint-dev/pylint pull request #9333
Opened 2023-12-29 06:31 UTC by mdbernard

- [x] Document your change, if it is a non-trivial one.
    * I would consider this change trivial, but this is my first PR to pylint, so please let me know if it would not be considered trivial by this repo's standards.
- [x] Relate your change to an issue in the tracker if such an issue exists
    * I did not find a related issue.
- [x] Write comprehensive commit messages and/or a good description of what the PR does.
- [x] Keep the change small, separate the consensual changes from the opinionated one.
  Don't hesitate to open multiple PRs if the change requires it. If your review is so
  big it requires to actually plan and allocate time to review, it's more likely
  that it's going to go stale.
- [x] If you used multiple emails or multiple names when contributing, add your mails
      and preferred name in ``script/.contributors_aliases.json``

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

Currently, `modified-iterating-set` only checks for when the `.add` or `.remove` methods are called on the set being iterated over. However, `.clear`, `.discard`, and `.pop` also raise `RuntimeError` when used on a set while it is being iterated over, so there is value in linting them as well.

2023-12-29 10:22 UTC, Pierre-Sassoulas requested changes
Great contribution, thank you !

2023-12-29 10:22 UTC, Pierre-Sassoulas commented on tests/functional/m/modified_iterating.py
> +    item_set.discard()  # [modified-iterating-set]
```suggestion
    item_set.discard(1)  # [modified-iterating-set]
```

2023-12-29 10:24 UTC, Pierre-Sassoulas commented
Here's an example of changelog : https://github.com/pylint-dev/pylint/blob/main/doc/whatsnew/fragments/8701.feature (you can refer to this merge request as there is no issue associated afaik)

2023-12-29 17:29 UTC, mdbernard commented
> Here's an example of changelog : https://github.com/pylint-dev/pylint/blob/main/doc/whatsnew/fragments/8701.feature (you can refer to this merge request with `Refs #9333` as there is no issue associated afaik)

(I made a new issue for this for ease of reference)

2023-12-30 07:44 UTC, Pierre-Sassoulas submitted a review, later dismissed

2023-12-30 07:44 UTC, Pierre-Sassoulas commented on doc/whatsnew/fragments/9334.feature
> +Check for `.clear`, `.discard`, and `.pop` methods being called on a set while it is being iterated over.
```suggestion
Check for `.clear`, `.discard`, `.pop` and `remove` methods being called on a set while it is being iterated over.
```

2023-12-30 07:57 UTC, Pierre-Sassoulas approved these changes

2023-12-30 07:59 UTC, Pierre-Sassoulas commented
Thank you for your work, very nice first contribution :thumbsup: this is going to be released in 3.1.0, congratulations on becoming a pylint contributor ;)

2023-12-30 08:04 UTC, merged