Catch ParentMissingError in variables checker
pylint-dev/pylint pull request #9371
Opened 2024-01-17 17:29 UTC by jacobtylerwalls

add compatibility with https://github.com/pylint-dev/astroid/pull/2345

some of the unrelated changes here are just for the sake of passing pylint too-many-statements, etc

2024-01-17 17:38 UTC, nickdrozd approved these changes
Fixes the problem for me!

2024-01-18 11:53 UTC, jacobtylerwalls commented
I think once we bump astroid these lines will be covered. I'm happy to wait to merge until then.

2024-01-28 12:09 UTC, cdce8p requested changes
Encountered the same error @nickdrozd has while testing. I'd recommend we merge this once all comments are addressed. The `astroid` update wouldn't be able to be merged before that anyway as with it some test cases would be failing (which are fixed with this change).

2024-01-28 12:09 UTC, cdce8p commented on pylint/checkers/variables.py
> +            except astroid.exceptions.ParentMissingError:
We should add `import astroid.exceptions` to the top of this file.

2024-01-28 12:09 UTC, cdce8p commented on pylint/checkers/variables.py
> +                return
Tbh I'm not sure this is really an improvement if it's just to work around the `too-many-statements` error. We already disable `too-many-branches` for this function, why not `too-many-statements` as well.

https://github.com/pylint-dev/pylint/blob/51c28bc922dfb8da42e680ed7190eb942889df01/pylint/checkers/variables.py#L2524-L2525

```diff
-    # pylint: disable = too-many-branches
+    # pylint: disable-next=too-many-branches,too-many-statements
```

2024-01-28 12:09 UTC, cdce8p commented on pylint/checkers/variables.py
> +            if not getattr(inferred, "elts", getattr(inferred, "items", [])):
Same here. Add the disable and revert afterwards.

2024-01-28 14:14 UTC, cdce8p commented on pylint/checkers/variables.py
> +    # pylint: disable = too-many-branches, too-many-statements
```suggestion
    # pylint: disable-next=too-many-branches,too-many-statements
```
The whitespace is up to you. I would just recommend to use `disable-next`.

2024-01-28 14:24 UTC, cdce8p approved these changes
Looks good! Thanks @jacobtylerwalls 👍🏻

2024-01-28 14:28 UTC, merged